const styles = StyleSheet.create({
  container: { flex: 1, padding: 20 },
  text: { fontSize: 24, fontWeight: 'bold' },
  header: { fontSize: 24, fontWeight: 'bold', marginBottom: 20, textAlign: 'center' },
  lessonCard: { backgroundColor: '#fff', borderRadius: 10, padding: 20, marginBottom: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 3.84, elevation: 5 },
  lessonHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  lessonTitle: { fontSize: 18, fontWeight: 'bold' },
  duration: { fontSize: 14, color: 'gray' },
  lessonDescription: { fontSize: 14, color: 'gray', marginBottom: 10 },
  videoButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#007AFF', padding: 10, borderRadius: 5, marginTop: 10 },
  videoButtonText: { fontSize: 14, fontWeight: 'bold', color: '#fff', marginLeft: 10 },
  quizContainer: { padding: 20 },
  questionText: { fontSize: 20, fontWeight: 'bold', marginBottom: 20 },
  optionButton: { backgroundColor: '#f8f9fa', padding: 15, borderRadius: 10, marginBottom: 10, borderWidth: 1, borderColor: '#dee2e6' },
  optionText: { fontSize: 16 },
  scoreContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  scoreText: { fontSize: 24, fontWeight: 'bold', marginBottom: 20 },
  restartButton: { backgroundColor: '#007AFF', padding: 15, borderRadius: 10 },
  buttonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  statsContainer: { padding: 20, backgroundColor: '#fff', borderRadius: 10, marginBottom: 20 },
  statsTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 10 },
  statsText: { fontSize: 16, marginBottom: 10 },
  progressBar: { height: 10, borderRadius: 5, overflow: 'hidden' },
  progressFill: { height: '100%' },
  badgesSection: { padding: 20 },
  badgesTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 15 },
  badgesList: { padding: 10 },
  badgeContainer: { width: BADGE_SIZE, height: BADGE_SIZE, borderRadius: BADGE_SIZE / 2, justifyContent: 'center', alignItems: 'center', margin: 10 },
  badgeIcon: { fontSize: 24, marginBottom: 5 },
  badgeName: { fontSize: 12, textAlign: 'center' }
}); 